/*
 * JUnit test case for bean TblBookCopies
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.TblBookCopies ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean TblBookCopies
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblBookCopiesTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class TblBookCopies getters and setters ..." );
		
		TblBookCopies tblBookCopies = new TblBookCopies();
		
		//--- Test setter/getter for field "bookid"  ( type : Integer )
		// System.out.println(" checking field bookid ..." );
		tblBookCopies.setBookid( integerValue ) ;
		Assert.assertTrue( integerValue == tblBookCopies.getBookid() ) ;

		//--- Test setter/getter for field "branchid"  ( type : Integer )
		// System.out.println(" checking field branchid ..." );
		tblBookCopies.setBranchid( integerValue ) ;
		Assert.assertTrue( integerValue == tblBookCopies.getBranchid() ) ;

		//--- Test setter/getter for field "noofcopies"  ( type : Integer )
		// System.out.println(" checking field noofcopies ..." );
		tblBookCopies.setNoofcopies( integerValue ) ;
		Assert.assertTrue( integerValue == tblBookCopies.getNoofcopies() ) ;

		
	}



}
