/*
 * JUnit test case for bean TblBorrower
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.TblBorrower ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean TblBorrower
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblBorrowerTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class TblBorrower getters and setters ..." );
		
		TblBorrower tblBorrower = new TblBorrower();
		
		//--- Test setter/getter for field "cardno"  ( type : Integer )
		// System.out.println(" checking field cardno ..." );
		tblBorrower.setCardno( integerValue ) ;
		Assert.assertTrue( integerValue == tblBorrower.getCardno() ) ;

		//--- Test setter/getter for field "name"  ( type : String )
		// System.out.println(" checking field name ..." );
		tblBorrower.setName( stringValue ) ;
		Assert.assertTrue( stringValue.equals( tblBorrower.getName() ) ) ;

		//--- Test setter/getter for field "address"  ( type : String )
		// System.out.println(" checking field address ..." );
		tblBorrower.setAddress( stringValue ) ;
		Assert.assertTrue( stringValue.equals( tblBorrower.getAddress() ) ) ;

		//--- Test setter/getter for field "phone"  ( type : String )
		// System.out.println(" checking field phone ..." );
		tblBorrower.setPhone( stringValue ) ;
		Assert.assertTrue( stringValue.equals( tblBorrower.getPhone() ) ) ;

		
	}



}
