/*
 * JUnit test case for bean TblBookLoans
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.TblBookLoans ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean TblBookLoans
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblBookLoansTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class TblBookLoans getters and setters ..." );
		
		TblBookLoans tblBookLoans = new TblBookLoans();
		
		//--- Test setter/getter for field "bookid"  ( type : Integer )
		// System.out.println(" checking field bookid ..." );
		tblBookLoans.setBookid( integerValue ) ;
		Assert.assertTrue( integerValue == tblBookLoans.getBookid() ) ;

		//--- Test setter/getter for field "branchid"  ( type : Integer )
		// System.out.println(" checking field branchid ..." );
		tblBookLoans.setBranchid( integerValue ) ;
		Assert.assertTrue( integerValue == tblBookLoans.getBranchid() ) ;

		//--- Test setter/getter for field "cardno"  ( type : Integer )
		// System.out.println(" checking field cardno ..." );
		tblBookLoans.setCardno( integerValue ) ;
		Assert.assertTrue( integerValue == tblBookLoans.getCardno() ) ;

		//--- Test setter/getter for field "dateout"  ( type : Date )
		// System.out.println(" checking field dateout ..." );
		tblBookLoans.setDateout( dateValue ) ;
		Assert.assertTrue( dateValue.equals( tblBookLoans.getDateout() ) );

		//--- Test setter/getter for field "duedate"  ( type : Date )
		// System.out.println(" checking field duedate ..." );
		tblBookLoans.setDuedate( dateValue ) ;
		Assert.assertTrue( dateValue.equals( tblBookLoans.getDuedate() ) );

		//--- Test setter/getter for field "datein"  ( type : Date )
		// System.out.println(" checking field datein ..." );
		tblBookLoans.setDatein( dateValue ) ;
		Assert.assertTrue( dateValue.equals( tblBookLoans.getDatein() ) );

		
	}



}
