/*
 * JUnit test case for bean TblGenre
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.TblGenre ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean TblGenre
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblGenreTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class TblGenre getters and setters ..." );
		
		TblGenre tblGenre = new TblGenre();
		
		//--- Test setter/getter for field "genreId"  ( type : Integer )
		// System.out.println(" checking field genreId ..." );
		tblGenre.setGenreId( integerValue ) ;
		Assert.assertTrue( integerValue == tblGenre.getGenreId() ) ;

		//--- Test setter/getter for field "genreName"  ( type : String )
		// System.out.println(" checking field genreName ..." );
		tblGenre.setGenreName( stringValue ) ;
		Assert.assertTrue( stringValue.equals( tblGenre.getGenreName() ) ) ;

		
	}



}
