/*
 * JUnit test case for bean TblLibraryBranch
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.TblLibraryBranch ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean TblLibraryBranch
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblLibraryBranchTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class TblLibraryBranch getters and setters ..." );
		
		TblLibraryBranch tblLibraryBranch = new TblLibraryBranch();
		
		//--- Test setter/getter for field "branchid"  ( type : Integer )
		// System.out.println(" checking field branchid ..." );
		tblLibraryBranch.setBranchid( integerValue ) ;
		Assert.assertTrue( integerValue == tblLibraryBranch.getBranchid() ) ;

		//--- Test setter/getter for field "branchname"  ( type : String )
		// System.out.println(" checking field branchname ..." );
		tblLibraryBranch.setBranchname( stringValue ) ;
		Assert.assertTrue( stringValue.equals( tblLibraryBranch.getBranchname() ) ) ;

		//--- Test setter/getter for field "branchaddress"  ( type : String )
		// System.out.println(" checking field branchaddress ..." );
		tblLibraryBranch.setBranchaddress( stringValue ) ;
		Assert.assertTrue( stringValue.equals( tblLibraryBranch.getBranchaddress() ) ) ;

		
	}



}
