/*
 * JUnit test case for bean TblPublisher
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.test.bean;


import java.math.BigDecimal;

import org.demo.bean.TblPublisher ;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean TblPublisher
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblPublisherTest 
{
	protected static final byte    byteValue    = 1 ;
	protected static final short   shortValue   = 1 ;
	protected static final int     intValue     = 1 ;
	protected static final int     integerValue = 1 ;
	protected static final long    longValue    = 1 ;
	
	protected static final float   floatValue    = 1.234f ;
	protected static final double  doubleValue   = 1.234 ;
	
	protected static final BigDecimal bigdecimalValue = new BigDecimal("12.3456");
	
	protected static final String  stringValue  = "A" ;
	
	protected static final java.util.Date     dateValue         = new java.util.Date();
	protected static final java.sql.Date      sqldateValue      = new java.sql.Date(dateValue.getTime());
	protected static final java.sql.Time      sqltimeValue      = new java.sql.Time(dateValue.getTime());
	protected static final java.sql.Timestamp sqltimestampValue = new java.sql.Timestamp(dateValue.getTime());

	protected static final byte[]  bytesArray  = "ABCD".getBytes() ;

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class TblPublisher getters and setters ..." );
		
		TblPublisher tblPublisher = new TblPublisher();
		
		//--- Test setter/getter for field "publisherid"  ( type : Integer )
		// System.out.println(" checking field publisherid ..." );
		tblPublisher.setPublisherid( integerValue ) ;
		Assert.assertTrue( integerValue == tblPublisher.getPublisherid() ) ;

		//--- Test setter/getter for field "publishername"  ( type : String )
		// System.out.println(" checking field publishername ..." );
		tblPublisher.setPublishername( stringValue ) ;
		Assert.assertTrue( stringValue.equals( tblPublisher.getPublishername() ) ) ;

		//--- Test setter/getter for field "publisheraddress"  ( type : String )
		// System.out.println(" checking field publisheraddress ..." );
		tblPublisher.setPublisheraddress( stringValue ) ;
		Assert.assertTrue( stringValue.equals( tblPublisher.getPublisheraddress() ) ) ;

		//--- Test setter/getter for field "publisherphone"  ( type : String )
		// System.out.println(" checking field publisherphone ..." );
		tblPublisher.setPublisherphone( stringValue ) ;
		Assert.assertTrue( stringValue.equals( tblPublisher.getPublisherphone() ) ) ;

		
	}



}
