/*
 * Java bean class for entity table tbl_borrower 
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.bean;

import java.io.Serializable;


/**
 * Entity bean for table "tbl_borrower"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblBorrower implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    cardno       ; // Primary Key

    private String     name         ;
    private String     address      ;
    private String     phone        ;

    /**
     * Default constructor
     */
    public TblBorrower()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "cardno" field value
     * This field is mapped on the database column "cardNo" ( type "INT", NotNull : true ) 
     * @param cardno
     */
	public void setCardno( Integer cardno )
    {
        this.cardno = cardno ;
    }
    /**
     * Get the "cardno" field value
     * This field is mapped on the database column "cardNo" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getCardno()
    {
        return this.cardno;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( VARCHAR ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "name" ( type "VARCHAR", NotNull : false ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "name" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : address ( VARCHAR ) 
    /**
     * Set the "address" field value
     * This field is mapped on the database column "address" ( type "VARCHAR", NotNull : false ) 
     * @param address
     */
    public void setAddress( String address )
    {
        this.address = address;
    }
    /**
     * Get the "address" field value
     * This field is mapped on the database column "address" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getAddress()
    {
        return this.address;
    }

    //--- DATABASE MAPPING : phone ( VARCHAR ) 
    /**
     * Set the "phone" field value
     * This field is mapped on the database column "phone" ( type "VARCHAR", NotNull : false ) 
     * @param phone
     */
    public void setPhone( String phone )
    {
        this.phone = phone;
    }
    /**
     * Get the "phone" field value
     * This field is mapped on the database column "phone" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getPhone()
    {
        return this.phone;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(cardno);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(phone);
        return sb.toString(); 
    } 


}
