/*
 * Java bean class for entity table tbl_book_loans 
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "tbl_book_loans"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblBookLoans implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    bookid       ; // Primary Key
    private Integer    branchid     ; // Primary Key
    private Integer    cardno       ; // Primary Key
    private Date       dateout      ; // Primary Key

    private Date       duedate      ;
    private Date       datein       ;

    /**
     * Default constructor
     */
    public TblBookLoans()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "bookid" field value
     * This field is mapped on the database column "bookId" ( type "INT", NotNull : true ) 
     * @param bookid
     */
	public void setBookid( Integer bookid )
    {
        this.bookid = bookid ;
    }
    /**
     * Get the "bookid" field value
     * This field is mapped on the database column "bookId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getBookid()
    {
        return this.bookid;
    }
    /**
     * Set the "branchid" field value
     * This field is mapped on the database column "branchId" ( type "INT", NotNull : true ) 
     * @param branchid
     */
	public void setBranchid( Integer branchid )
    {
        this.branchid = branchid ;
    }
    /**
     * Get the "branchid" field value
     * This field is mapped on the database column "branchId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getBranchid()
    {
        return this.branchid;
    }
    /**
     * Set the "cardno" field value
     * This field is mapped on the database column "cardNo" ( type "INT", NotNull : true ) 
     * @param cardno
     */
	public void setCardno( Integer cardno )
    {
        this.cardno = cardno ;
    }
    /**
     * Get the "cardno" field value
     * This field is mapped on the database column "cardNo" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getCardno()
    {
        return this.cardno;
    }
    /**
     * Set the "dateout" field value
     * This field is mapped on the database column "dateOut" ( type "DATETIME", NotNull : true ) 
     * @param dateout
     */
	public void setDateout( Date dateout )
    {
        this.dateout = dateout ;
    }
    /**
     * Get the "dateout" field value
     * This field is mapped on the database column "dateOut" ( type "DATETIME", NotNull : true ) 
     * @return the field value
     */
	public Date getDateout()
    {
        return this.dateout;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : dueDate ( DATETIME ) 
    /**
     * Set the "duedate" field value
     * This field is mapped on the database column "dueDate" ( type "DATETIME", NotNull : false ) 
     * @param duedate
     */
    public void setDuedate( Date duedate )
    {
        this.duedate = duedate;
    }
    /**
     * Get the "duedate" field value
     * This field is mapped on the database column "dueDate" ( type "DATETIME", NotNull : false ) 
     * @return the field value
     */
    public Date getDuedate()
    {
        return this.duedate;
    }

    //--- DATABASE MAPPING : dateIn ( DATETIME ) 
    /**
     * Set the "datein" field value
     * This field is mapped on the database column "dateIn" ( type "DATETIME", NotNull : false ) 
     * @param datein
     */
    public void setDatein( Date datein )
    {
        this.datein = datein;
    }
    /**
     * Get the "datein" field value
     * This field is mapped on the database column "dateIn" ( type "DATETIME", NotNull : false ) 
     * @return the field value
     */
    public Date getDatein()
    {
        return this.datein;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(bookid);
        sb.append("|");
        sb.append(branchid);
        sb.append("|");
        sb.append(cardno);
        sb.append("|");
        sb.append(dateout);
        sb.append("|");
        sb.append(duedate);
        sb.append("|");
        sb.append(datein);
        return sb.toString(); 
    } 


}
