/*
 * Java bean class for entity table tbl_book_copies 
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.bean;

import java.io.Serializable;


/**
 * Entity bean for table "tbl_book_copies"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblBookCopies implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    bookid       ; // Primary Key
    private Integer    branchid     ; // Primary Key

    private Integer    noofcopies   ;

    /**
     * Default constructor
     */
    public TblBookCopies()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "bookid" field value
     * This field is mapped on the database column "bookId" ( type "INT", NotNull : true ) 
     * @param bookid
     */
	public void setBookid( Integer bookid )
    {
        this.bookid = bookid ;
    }
    /**
     * Get the "bookid" field value
     * This field is mapped on the database column "bookId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getBookid()
    {
        return this.bookid;
    }
    /**
     * Set the "branchid" field value
     * This field is mapped on the database column "branchId" ( type "INT", NotNull : true ) 
     * @param branchid
     */
	public void setBranchid( Integer branchid )
    {
        this.branchid = branchid ;
    }
    /**
     * Get the "branchid" field value
     * This field is mapped on the database column "branchId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getBranchid()
    {
        return this.branchid;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : noOfCopies ( INT ) 
    /**
     * Set the "noofcopies" field value
     * This field is mapped on the database column "noOfCopies" ( type "INT", NotNull : false ) 
     * @param noofcopies
     */
    public void setNoofcopies( Integer noofcopies )
    {
        this.noofcopies = noofcopies;
    }
    /**
     * Get the "noofcopies" field value
     * This field is mapped on the database column "noOfCopies" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getNoofcopies()
    {
        return this.noofcopies;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(bookid);
        sb.append("|");
        sb.append(branchid);
        sb.append("|");
        sb.append(noofcopies);
        return sb.toString(); 
    } 


}
