/*
 * Java bean class for entity table tbl_book_authors 
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.bean;

import java.io.Serializable;


/**
 * Entity bean for table "tbl_book_authors"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblBookAuthors implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    bookid       ; // Primary Key
    private Integer    authorid     ; // Primary Key


    /**
     * Default constructor
     */
    public TblBookAuthors()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "bookid" field value
     * This field is mapped on the database column "bookId" ( type "INT", NotNull : true ) 
     * @param bookid
     */
	public void setBookid( Integer bookid )
    {
        this.bookid = bookid ;
    }
    /**
     * Get the "bookid" field value
     * This field is mapped on the database column "bookId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getBookid()
    {
        return this.bookid;
    }
    /**
     * Set the "authorid" field value
     * This field is mapped on the database column "authorId" ( type "INT", NotNull : true ) 
     * @param authorid
     */
	public void setAuthorid( Integer authorid )
    {
        this.authorid = authorid ;
    }
    /**
     * Get the "authorid" field value
     * This field is mapped on the database column "authorId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getAuthorid()
    {
        return this.authorid;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(bookid);
        sb.append("|");
        sb.append(authorid);
        return sb.toString(); 
    } 


}
