/*
 * Java bean class for entity table tbl_book 
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.bean;

import java.io.Serializable;


/**
 * Entity bean for table "tbl_book"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblBook implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    bookid       ; // Primary Key

    private String     title        ;
    private Integer    pubid        ;

    /**
     * Default constructor
     */
    public TblBook()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "bookid" field value
     * This field is mapped on the database column "bookId" ( type "INT", NotNull : true ) 
     * @param bookid
     */
	public void setBookid( Integer bookid )
    {
        this.bookid = bookid ;
    }
    /**
     * Get the "bookid" field value
     * This field is mapped on the database column "bookId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getBookid()
    {
        return this.bookid;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : title ( VARCHAR ) 
    /**
     * Set the "title" field value
     * This field is mapped on the database column "title" ( type "VARCHAR", NotNull : true ) 
     * @param title
     */
    public void setTitle( String title )
    {
        this.title = title;
    }
    /**
     * Get the "title" field value
     * This field is mapped on the database column "title" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getTitle()
    {
        return this.title;
    }

    //--- DATABASE MAPPING : pubId ( INT ) 
    /**
     * Set the "pubid" field value
     * This field is mapped on the database column "pubId" ( type "INT", NotNull : false ) 
     * @param pubid
     */
    public void setPubid( Integer pubid )
    {
        this.pubid = pubid;
    }
    /**
     * Get the "pubid" field value
     * This field is mapped on the database column "pubId" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getPubid()
    {
        return this.pubid;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(bookid);
        sb.append("|");
        sb.append(title);
        sb.append("|");
        sb.append(pubid);
        return sb.toString(); 
    } 


}
