/*
 * Java bean class for entity table tbl_genre 
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.bean;

import java.io.Serializable;


/**
 * Entity bean for table "tbl_genre"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblGenre implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    genreId      ; // Primary Key

    private String     genreName    ;

    /**
     * Default constructor
     */
    public TblGenre()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "genreId" field value
     * This field is mapped on the database column "genre_id" ( type "INT", NotNull : true ) 
     * @param genreId
     */
	public void setGenreId( Integer genreId )
    {
        this.genreId = genreId ;
    }
    /**
     * Get the "genreId" field value
     * This field is mapped on the database column "genre_id" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getGenreId()
    {
        return this.genreId;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : genre_name ( VARCHAR ) 
    /**
     * Set the "genreName" field value
     * This field is mapped on the database column "genre_name" ( type "VARCHAR", NotNull : false ) 
     * @param genreName
     */
    public void setGenreName( String genreName )
    {
        this.genreName = genreName;
    }
    /**
     * Get the "genreName" field value
     * This field is mapped on the database column "genre_name" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getGenreName()
    {
        return this.genreName;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(genreId);
        sb.append("|");
        sb.append(genreName);
        return sb.toString(); 
    } 


}
