/*
 * Java bean class for entity table tbl_library_branch 
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.bean;

import java.io.Serializable;


/**
 * Entity bean for table "tbl_library_branch"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblLibraryBranch implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    branchid     ; // Primary Key

    private String     branchname   ;
    private String     branchaddress ;

    /**
     * Default constructor
     */
    public TblLibraryBranch()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "branchid" field value
     * This field is mapped on the database column "branchId" ( type "INT", NotNull : true ) 
     * @param branchid
     */
	public void setBranchid( Integer branchid )
    {
        this.branchid = branchid ;
    }
    /**
     * Get the "branchid" field value
     * This field is mapped on the database column "branchId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getBranchid()
    {
        return this.branchid;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : branchName ( VARCHAR ) 
    /**
     * Set the "branchname" field value
     * This field is mapped on the database column "branchName" ( type "VARCHAR", NotNull : false ) 
     * @param branchname
     */
    public void setBranchname( String branchname )
    {
        this.branchname = branchname;
    }
    /**
     * Get the "branchname" field value
     * This field is mapped on the database column "branchName" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getBranchname()
    {
        return this.branchname;
    }

    //--- DATABASE MAPPING : branchAddress ( VARCHAR ) 
    /**
     * Set the "branchaddress" field value
     * This field is mapped on the database column "branchAddress" ( type "VARCHAR", NotNull : false ) 
     * @param branchaddress
     */
    public void setBranchaddress( String branchaddress )
    {
        this.branchaddress = branchaddress;
    }
    /**
     * Get the "branchaddress" field value
     * This field is mapped on the database column "branchAddress" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getBranchaddress()
    {
        return this.branchaddress;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(branchid);
        sb.append("|");
        sb.append(branchname);
        sb.append("|");
        sb.append(branchaddress);
        return sb.toString(); 
    } 


}
