/*
 * Java bean class for entity table tbl_publisher 
 * Created on 1 Aug 2017 ( Date ISO 2017-08-01 - Time 21:57:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.bean;

import java.io.Serializable;


/**
 * Entity bean for table "tbl_publisher"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblPublisher implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    publisherid  ; // Primary Key

    private String     publishername ;
    private String     publisheraddress ;
    private String     publisherphone ;

    /**
     * Default constructor
     */
    public TblPublisher()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "publisherid" field value
     * This field is mapped on the database column "publisherId" ( type "INT", NotNull : true ) 
     * @param publisherid
     */
	public void setPublisherid( Integer publisherid )
    {
        this.publisherid = publisherid ;
    }
    /**
     * Get the "publisherid" field value
     * This field is mapped on the database column "publisherId" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getPublisherid()
    {
        return this.publisherid;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : publisherName ( VARCHAR ) 
    /**
     * Set the "publishername" field value
     * This field is mapped on the database column "publisherName" ( type "VARCHAR", NotNull : true ) 
     * @param publishername
     */
    public void setPublishername( String publishername )
    {
        this.publishername = publishername;
    }
    /**
     * Get the "publishername" field value
     * This field is mapped on the database column "publisherName" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getPublishername()
    {
        return this.publishername;
    }

    //--- DATABASE MAPPING : publisherAddress ( VARCHAR ) 
    /**
     * Set the "publisheraddress" field value
     * This field is mapped on the database column "publisherAddress" ( type "VARCHAR", NotNull : false ) 
     * @param publisheraddress
     */
    public void setPublisheraddress( String publisheraddress )
    {
        this.publisheraddress = publisheraddress;
    }
    /**
     * Get the "publisheraddress" field value
     * This field is mapped on the database column "publisherAddress" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getPublisheraddress()
    {
        return this.publisheraddress;
    }

    //--- DATABASE MAPPING : publisherPhone ( VARCHAR ) 
    /**
     * Set the "publisherphone" field value
     * This field is mapped on the database column "publisherPhone" ( type "VARCHAR", NotNull : false ) 
     * @param publisherphone
     */
    public void setPublisherphone( String publisherphone )
    {
        this.publisherphone = publisherphone;
    }
    /**
     * Get the "publisherphone" field value
     * This field is mapped on the database column "publisherPhone" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getPublisherphone()
    {
        return this.publisherphone;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(publisherid);
        sb.append("|");
        sb.append(publishername);
        sb.append("|");
        sb.append(publisheraddress);
        sb.append("|");
        sb.append(publisherphone);
        return sb.toString(); 
    } 


}
